# Generated by Django 5.1.4 on 2025-01-02 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.district')),
            ],
        ),
    ]
