# Generated by Django 5.1.4 on 2025-01-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.TextField()),
                ('nomEtab', models.CharField(max_length=255)),
                ('TypeEtab', models.CharField(choices=[('EPP', 'EPP'), ('CEG', 'CEG'), ('LYCEE', 'LYCEE'), ('ADMINISTRATIF', 'ADMINISTRATIF'), ('ESM', 'ESM'), ('AUTRES', 'AUTRES')], max_length=25)),
                ('fokontany', models.CharField(max_length=255, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.commune')),
            ],
        ),
    ]
