# Generated by Django 5.1.4 on 2025-01-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_alter_commune_create_on_alter_district_create_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numMarche', models.CharField(max_length=255, null=True)),
                ('NbSalle', models.CharField(max_length=10)),
                ('Titulaire', models.CharField(max_length=255, null=True)),
                ('NumTitulaire', models.CharField(max_length=50, null=True)),
                ('delaiEx', models.CharField(max_length=50, null=True)),
                ('batiment', models.CharField(choices=[('Administratif', 'Administratif'), ('Scolaire', 'Scolaire')], max_length=25)),
                ('travaux', models.CharField(choices=[('Constr. Neuve', 'Constr. Neuve'), ('Rehabilitation', 'Rehabilitation')], max_length=25)),
                ('financement', models.CharField(choices=[('RPI', 'RPI'), ('PAEB', 'PAEB')], max_length=25)),
                ('os', models.CharField(choices=[('OS_2019', 'OS_2019'), ('OS_2020', 'OS_2020'), ('OS_2021', 'OS_2021'), ('OS_2022', 'OS_2022'), ('OS_2023', 'OS_2023'), ('OS_2024', 'OS_2024'), ('OS_2025', 'OS_2025'), ('OS_PAEB', 'OS_PAEB')], max_length=25)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.site')),
            ],
        ),
    ]
