# Generated by Django 5.1.4 on 2025-01-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_avancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancement',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='constructionImg/'),
        ),
        migrations.AddField(
            model_name='avancement',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='constructionImg/'),
        ),
        migrations.AddField(
            model_name='avancement',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='constructionImg/'),
        ),
        migrations.AddField(
            model_name='avancement',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='constructionImg/'),
        ),
    ]
