# Generated by Django 5.1.4 on 2025-01-03 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_avancement_photo1_avancement_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancement',
            name='AnneeAchevement',
        ),
        migrations.RemoveField(
            model_name='avancement',
            name='Observation',
        ),
        migrations.AddField(
            model_name='avancement',
            name='annee_achevement',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message="L'année doit comporter 4 chiffres.")]),
        ),
        migrations.AlterField(
            model_name='avancement',
            name='avancement',
            field=models.IntegerField(help_text='Avancement en pourcentage (0 à 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='avancement',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
