# Generated by Django 5.1.4 on 2025-01-04 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_remove_avancement_anneeachevement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='annee_achevement',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message="L'année doit comporter 4 chiffres.")]),
        ),
    ]
