# Generated by Django 5.1.4 on 2025-01-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_alter_avancement_annee_achevement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.CharField(max_length=100)),
                ('TypeEtab', models.CharField()),
                ('service', models.CharField(choices=[('Bureau Rattaché', 'Bureau Rattaché'), ('SCMIS', 'SCMIS'), ('SCMIA', 'SCMIA'), ('SDSA', 'SDSA'), ('PAEB', 'PAEB')], default='Bureau Rattaché', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('justification', models.TextField(blank=True, null=True)),
                ('fond', models.FileField(blank=True, null=True, upload_to='demandeconge/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.personnel')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.typeconge')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('quota_total', models.PositiveIntegerField(default=30)),
                ('quota_utilise', models.PositiveIntegerField(default=0)),
                ('fond', models.FileField(blank=True, null=True, upload_to='decision/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.personnel')),
            ],
            options={
                'unique_together': {('utilisateur', 'annee')},
            },
        ),
    ]
