# Generated by Django 5.1.4 on 2025-01-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_personnel_typeconge_conge_quotaannuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='TypeEtab',
        ),
    ]
