# Generated by Django 5.1.4 on 2025-01-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_remove_personnel_typeetab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='NbSalle',
            field=models.IntegerField(max_length=10),
        ),
    ]
