# Generated by Django 5.1.4 on 2025-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_remove_personnel_typeetab'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancement',
            name='n_stat',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], default='O', max_length=2),
        ),
    ]
