# Generated by Django 5.1.4 on 2025-01-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_avancement_n_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='NbSalle',
            field=models.IntegerField(max_length=10),
        ),
    ]
