# Generated by Django 5.1.4 on 2025-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_alter_marche_nbsalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpsGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=10)),
                ('corps', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['district__region__province__name', 'district__region__name', 'district__region__district__name']},
        ),
    ]
