# Generated by Django 5.1.4 on 2025-01-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0013_corpsgrade_alter_commune_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('fond', models.FileField(blank=True, null=True, upload_to='fondCariere/')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.corpsgrade')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.personnel')),
            ],
            options={
                'ordering': ['personnel__nom'],
            },
        ),
    ]
