# Generated by Django 5.1.4 on 2025-01-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0014_carriere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carriere',
            options={'ordering': ['personnel__nom', '-date_debut']},
        ),
        migrations.CreateModel(
            name='OM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('dureedep', models.PositiveIntegerField()),
                ('moyendep', models.CharField(max_length=255)),
                ('motif', models.TextField()),
                ('datedep', models.DateField(blank=True, null=True)),
                ('financement', models.CharField(blank=True, max_length=255, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('fondOM', models.FileField(blank=True, null=True, upload_to='fondOM/')),
                ('fondOR', models.FileField(blank=True, null=True, upload_to='fondOR/')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.personnel')),
            ],
            options={
                'ordering': ['-datedep', 'personnel__nom'],
            },
        ),
    ]
