# Generated by Django 5.1.4 on 2025-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0015_alter_carriere_options_om'),
    ]

    operations = [
        migrations.AddField(
            model_name='om',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
